// <auto-generated />
using System;
using BuilderPulsePro.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BuilderPulsePro.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260206054107_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BuilderPulsePro.Api.Domain.Contractor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Point>("HomeBase")
                        .IsRequired()
                        .HasColumnType("geography (point)");

                    b.Property<int>("ServiceRadiusMeters")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HomeBase");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("HomeBase"), "gist");

                    b.ToTable("Contractors");
                });

            modelBuilder.Entity("BuilderPulsePro.Api.Domain.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("SiteLocation")
                        .IsRequired()
                        .HasColumnType("geography (point)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Trade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("SiteLocation");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SiteLocation"), "gist");

                    b.ToTable("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
